# Generated by Django 5.1.3 on 2024-11-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dni",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
