# Generated by Django 5.1 on 2024-11-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_dni"),
        ("authentication", "0003_seeders"),
    ]

    operations = []
