# Generated by Django 5.1.3 on 2024-11-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("rooms", "0004_reserva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.user"
            ),
        ),
    ]
