# Generated by Django 5.1 on 2024-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asunto',
            field=models.CharField(default='No especificado', max_length=255, verbose_name='Asunto de la reserva'),
        ),
    ]
